/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Slate */
        get: operations["slate_api_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/filtered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filtered
         * @description What the gate removed, and why — retained so the bar stays auditable.
         */
        get: operations["filtered_api_queue_filtered_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Approved and waiting for the human to apply. Nothing here has been sent.
         */
        get: operations["ready_api_queue_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show */
        get: operations["show_api_queue__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{entry_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Approve for the ready tray. Contacts no employer and submits nothing.
         */
        post: operations["approve_api_queue__entry_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{entry_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_queue__entry_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{entry_id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snooze */
        post: operations["snooze_api_queue__entry_id__snooze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{entry_id}/unapprove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unapprove
         * @description 'I changed my mind' — back to the queue, nothing recorded as sent.
         */
        post: operations["unapprove_api_queue__entry_id__unapprove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{entry_id}/paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Paste
         * @description Upgrade a link-only entry with a description the human supplied, then re-score.
         */
        post: operations["paste_api_queue__entry_id__paste_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/{entry_id}/submitted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submitted
         * @description Record that the HUMAN submitted this application.
         *
         *     The only route that can reach the `submitted` state, and it records a fact rather than
         *     causing one. Nothing here contacts an employer. CLAUDE.md constraint 1.
         */
        post: operations["submitted_api_queue__entry_id__submitted_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application Stats */
        get: operations["application_stats_api_applications_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Csv
         * @description Download the history as CSV.
         *
         *     utf-8-sig so Excel reads the encoding correctly on a double-click rather than mangling
         *     accented company names.
         */
        get: operations["export_csv_api_applications_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update
         * @description Record what came back. Answering the OA question is what trains the prediction.
         */
        patch: operations["update_api_applications__app_id__patch"];
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumes */
        get: operations["resumes_api_resumes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Interests */
        get: operations["interests_api_interests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Boards */
        get: operations["boards_api_boards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Run
         * @description Discover, score, and queue. Submits nothing — see CLAUDE.md constraint 1.
         */
        post: operations["trigger_run_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationOut */
        ApplicationOut: {
            /** Id */
            id: number;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Location */
            location?: string | null;
            /** Source */
            source: string;
            /** Apply Url */
            apply_url?: string | null;
            /** Submitted At */
            submitted_at: string;
            /** Submission Channel */
            submission_channel?: string | null;
            /** Resume Used */
            resume_used?: string | null;
            /** Fit Score At Submit */
            fit_score_at_submit?: number | null;
            /** Oa Expected */
            oa_expected: string;
            /** Oa Received */
            oa_received?: boolean | null;
            /** Oa Received At */
            oa_received_at?: string | null;
            /** Oa Platform */
            oa_platform?: string | null;
            /** Oa Due At */
            oa_due_at?: string | null;
            /** Outcome */
            outcome: string;
            /** Outcome At */
            outcome_at?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ApplicationUpdateIn */
        ApplicationUpdateIn: {
            outcome?: components["schemas"]["Outcome"] | null;
            /** Oa Received */
            oa_received?: boolean | null;
            /** Oa Platform */
            oa_platform?: string | null;
            /** Oa Due At */
            oa_due_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Submission Channel */
            submission_channel?: string | null;
        };
        /** ApproveIn */
        ApproveIn: {
            /** Note */
            note?: string | null;
        };
        /**
         * DimensionScore
         * @description One scored dimension, with the evidence that produced it.
         *
         *     The evidence is not decoration: an unexplained score trains the user to rubber-stamp the
         *     queue, which defeats the human-in-the-loop that constraint 1 depends on.
         */
        DimensionScore: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Weight */
            weight: number;
            /** Evidence */
            evidence: string;
        };
        /** Education */
        Education: {
            /** School */
            school?: string | null;
            /** Degree */
            degree?: string | null;
            /** Degree Level */
            degree_level?: string | null;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Graduation */
            graduation?: string | null;
            /** Source Span */
            source_span?: string | null;
        };
        /** Employment */
        Employment: {
            /** Employer */
            employer?: string | null;
            /** Title */
            title?: string | null;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /** Source Span */
            source_span?: string | null;
        };
        /** Exclusions */
        Exclusions: {
            /** Companies */
            companies?: string[];
            /** Title Keywords */
            title_keywords?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardFilters */
        HardFilters: {
            /** Degree Level Min */
            degree_level_min?: string | null;
            /** Seniority */
            seniority?: string[];
            /**
             * Citizenship Required Ok
             * @default true
             */
            citizenship_required_ok: boolean;
            /**
             * Clearance Required Ok
             * @default false
             */
            clearance_required_ok: boolean;
            /** Employment Types */
            employment_types?: string[];
        };
        /**
         * Interests
         * @description Declared targeting. Runtime input, never repository configuration.
         */
        Interests: {
            /** Role Families */
            role_families?: components["schemas"]["RoleFamily"][];
            /** Industries */
            industries?: string[];
            locations?: components["schemas"]["LocationPrefs"];
            hard_filters?: components["schemas"]["HardFilters"];
            exclusions?: components["schemas"]["Exclusions"];
            throughput?: components["schemas"]["Throughput"];
        };
        /** LocationPrefs */
        LocationPrefs: {
            /**
             * Remote
             * @default true
             */
            remote: boolean;
            /** Home */
            home?: string | null;
            /**
             * Max Distance Miles
             * @default 50
             */
            max_distance_miles: number | null;
            /** Places */
            places?: components["schemas"]["PlacePref"][];
            /** Metros */
            metros?: string[];
            /**
             * Relocation
             * @default no
             */
            relocation: string;
        };
        /** OAEvidence */
        OAEvidence: {
            /** Kind */
            kind: string;
            /** Detail */
            detail: string;
            /** Quote */
            quote?: string | null;
        };
        /**
         * Outcome
         * @enum {string}
         */
        Outcome: "pending" | "oa" | "interview" | "offer" | "rejected" | "ghosted" | "withdrawn";
        /** PasteIn */
        PasteIn: {
            /** Text */
            text: string;
        };
        /**
         * PlacePref
         * @description One place or state you're interested in, and how much.
         *
         *     Weight works the way `RoleFamily.weight` does, so "how much do I want this" has a single
         *     meaning across the whole config.
         */
        PlacePref: {
            /** Place */
            place?: string | null;
            /** State */
            state?: string | null;
            /**
             * Weight
             * @default 1
             */
            weight: number;
        };
        /**
         * Profile
         * @description The structured resume parse. Written to profile.yaml and hand-editable thereafter.
         */
        Profile: {
            /** Name */
            name?: string | null;
            /** Skills */
            skills?: string[];
            /** Education */
            education?: components["schemas"]["Education"][];
            /** Employment */
            employment?: components["schemas"]["Employment"][];
            /** Highest Degree Level */
            highest_degree_level?: string | null;
            /** Seniority */
            seniority?: string | null;
            /** Locations */
            locations?: string[];
            /** Parsed From */
            parsed_from?: string[];
            /** Notes */
            notes?: string | null;
        };
        /**
         * QueueEntryOut
         * @description Every list field here is always populated by the route, so none carry a default:
         *     an optional field in the schema becomes an optional type in the SPA, which would force
         *     null-checks against a guarantee the server does keep.
         */
        QueueEntryOut: {
            /** Id */
            id: number;
            /** State */
            state: string;
            /** Source */
            source: string;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Locations */
            locations: string[];
            /** Remote */
            remote: boolean;
            /** Posted At */
            posted_at?: string | null;
            /** Posted At Precision */
            posted_at_precision: string;
            /** Apply Url */
            apply_url: string;
            /** Department */
            department?: string | null;
            /** Compensation */
            compensation?: string | null;
            /** Description Text */
            description_text?: string | null;
            /** Description Source */
            description_source?: string | null;
            /** Completeness */
            completeness: string;
            /** Provenance Note */
            provenance_note?: string | null;
            /** Also Seen In */
            also_seen_in: string[];
            /** Fit Score */
            fit_score?: number | null;
            /** Score Confidence */
            score_confidence: string;
            /** Rank Score */
            rank_score?: number | null;
            /** Recency Factor */
            recency_factor?: number | null;
            /** Dimensions */
            dimensions: components["schemas"]["DimensionScore"][];
            /** Matched Signals */
            matched_signals: string[];
            /** Missing Signals */
            missing_signals: string[];
            /** Role Family */
            role_family?: string | null;
            /** Adjudication Note */
            adjudication_note?: string | null;
            /** Oa Expected */
            oa_expected: string;
            /** Oa Expectation Confidence */
            oa_expectation_confidence: string;
            /** Oa Expectation Evidence */
            oa_expectation_evidence: components["schemas"]["OAEvidence"][];
            recommended_resume?: components["schemas"]["ResumeOut"] | null;
            runner_up_resume?: components["schemas"]["ResumeOut"] | null;
            /** Selection Rationale */
            selection_rationale?: string | null;
            /** Filter Reason */
            filter_reason?: string | null;
            /** State Changed At */
            state_changed_at: string;
        };
        /** RejectIn */
        RejectIn: {
            reason: components["schemas"]["RejectionReason"];
            /** Note */
            note?: string | null;
        };
        /**
         * RejectionReason
         * @enum {string}
         */
        RejectionReason: "wrong_seniority" | "wrong_location" | "wrong_industry" | "not_this_company" | "already_applied" | "stale_posting" | "compensation" | "other";
        /** ResumeOut */
        ResumeOut: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Path */
            path: string;
            /** Is Master */
            is_master: boolean;
            /** Emphasis Summary */
            emphasis_summary: string;
        };
        /** RoleFamily */
        RoleFamily: {
            /** Name */
            name: string;
            /**
             * Weight
             * @default 1
             */
            weight: number;
            /** Keywords */
            keywords?: string[];
            /** Min Fit */
            min_fit?: number | null;
        };
        /** RunIn */
        RunIn: {
            /**
             * Use Llm
             * @default false
             */
            use_llm: boolean;
            /**
             * Use Research
             * @default false
             */
            use_research: boolean;
        };
        /** RunOut */
        RunOut: {
            /** Postings Seen */
            postings_seen: number;
            /** New Entries */
            new_entries: number;
            /** Queued */
            queued: number;
            /** Filtered */
            filtered: number;
            /** Boards Added */
            boards_added: number;
            /** Expired */
            expired: number;
            /** Errors */
            errors: string[];
            /** Summary */
            summary: string;
        };
        /** SlateOut */
        SlateOut: {
            /** Entries */
            entries: components["schemas"]["QueueEntryOut"][];
            /** Slate Size */
            slate_size: number;
            /** Submissions Per Day */
            submissions_per_day: number;
            /** Total Queued */
            total_queued: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** SnoozeIn */
        SnoozeIn: {
            /**
             * Days
             * @default 3
             */
            days: number;
        };
        /** StatsOut */
        StatsOut: {
            /** Total */
            total: number;
            /** By Outcome */
            by_outcome: {
                [key: string]: number;
            };
            /** Oa Received */
            oa_received: number;
            /** Oa Known */
            oa_known: number;
        };
        /**
         * SubmitIn
         * @description Recording a submission the human already made. The tool never initiates one.
         */
        SubmitIn: {
            /** Channel */
            channel?: string | null;
            /** Note */
            note?: string | null;
        };
        /** Throughput */
        Throughput: {
            /**
             * Submissions Per Day
             * @default 5
             */
            submissions_per_day: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    slate_api_queue_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filtered_api_queue_filtered_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_api_queue_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryOut"][];
                };
            };
        };
    };
    show_api_queue__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_queue__entry_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_queue__entry_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snooze_api_queue__entry_id__snooze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnoozeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unapprove_api_queue__entry_id__unapprove_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paste_api_queue__entry_id__paste_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitted_api_queue__entry_id__submitted_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_applications_get: {
        parameters: {
            query?: {
                outcome?: string | null;
                company?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_stats_api_applications_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    export_csv_api_applications_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_api_applications__app_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumes_api_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeOut"][];
                };
            };
        };
    };
    profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    interests_api_interests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Interests"];
                };
            };
        };
    };
    boards_api_boards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    trigger_run_api_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
